server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.211.55.14:3306/test?characterEncoding=utf-8
    username: test
    password: daydayup
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path:
      - classpath:/templates/
